# Generated by Django 6.1 on 2026-09-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='students_enrolled',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
