# Generated by Django 6.1 on 2026-09-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_students_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='notes',
            new_name='personal_info',
        ),
    ]
