# Generated by Django 6.1 on 2026-09-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_enrollment_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='students_enrolled',
        ),
    ]
