# Generated by Django 6.1 on 2026-09-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_notes_student_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
