# Generated by Django 6.1 on 2026-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_enrollment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('Spring 2026', 'Spring 2026'), ('Fall 2026', 'Fall 2026'), ('Spring 2027', 'Spring 2027'), ('Fall 2027', 'Fall 2027')], max_length=20),
        ),
    ]
