# Generated by Django 6.1 on 2026-09-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_created_at_teacher_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
    ]
