# Generated by Django 6.1 on 2026-09-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
